---
- name: install package across all machines
  hosts: all
  become: true
  tasks:
  - name: install apache package
    apt:
     name: apache2
     state: latest
     dep: all
     pack: list
     state: restarted
  - name: enable apache package
    service:
       name: apache2
       enabled: yes
  - name: copy
    copy:
      src:
      dest:
